sodu: require
services:
  - docker
before_install:
  # Build image for testing client
  - docker build -t continuestudying/test-client -f ./client/Dockerfile.dev ./client
script:
  - docker run continuestudying/test-client npm test -- --coverage
after_success:
  # Build images
  - docker build -t continuestudying/multi-client-review ./client
  - docker build -t continuestudying/multi-nginx-review ./nginx
  - docker build -t continuestudying/multi-server-review ./server
  - docker build -t continuestudying/multi-worker-review ./worker
  
  # Login Docker Hub
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

  # Push those images to Docker Hub
  - docker push continuestudying/multi-client-review
  - docker push continuestudying/multi-nginx-review
  - docker push continuestudying/multi-server-review
  - docker push continuestudying/multi-worker-review

deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: multi-docker-review
  env: MultiDockerReview-env
  bucket_name: elasticbeanstalk-us-east-2-572689041991
  bucket_path: docker-multi-review
  on:
    branch: master
  access_key_id:
    secure: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
